// ═══════════════════════════════════════════════════════════════
// POLARA — Demo Data
// All data is clearly synthetic demonstration data
// ═══════════════════════════════════════════════════════════════

import {
  User, Expedition, Resource, Report, Dataset, Publication,
  Photograph, Video, LearningModule, GlossaryTerm, ResearchArea,
  Notification, OutreachPackage, Quiz
} from './types';

// ── Demo Users ──
export const demoUsers: User[] = [
  {
    id: 'u1',
    name: 'Dr. Priya Sharma',
    email: 'admin@polara.demo',
    role: 'admin',
    institution: 'NCPOR, Goa',
    researchAreas: ['Climate Science', 'Glaciology'],
  },
  {
    id: 'u2',
    name: 'Dr. Arjun Mehta',
    email: 'researcher@polara.demo',
    role: 'researcher',
    institution: 'NCPOR, Goa',
    researchAreas: ['Oceanography', 'Polar Biology'],
  },
  {
    id: 'u3',
    name: 'Prof. Kavita Nair',
    email: 'educator@polara.demo',
    role: 'educator',
    institution: 'IIT Bombay',
    researchAreas: ['Earth Sciences', 'Climate Science'],
  },
  {
    id: 'u4',
    name: 'Rohan Patel',
    email: 'student@polara.demo',
    role: 'student',
    institution: 'University of Delhi',
    researchAreas: ['Polar Biology'],
  },
];

// ── Research Areas ──
export const researchAreas: ResearchArea[] = [
  { id: 'ra1', name: 'Oceanography', icon: '🌊', description: 'Study of the physical and biological aspects of polar oceans', resourceCount: 42, color: '#38b6e6' },
  { id: 'ra2', name: 'Glaciology', icon: '🧊', description: 'Study of ice sheets, glaciers, and sea ice dynamics', resourceCount: 38, color: '#5cc9ef' },
  { id: 'ra3', name: 'Climate Science', icon: '🌡', description: 'Understanding polar climate systems and their global impact', resourceCount: 56, color: '#2ec4b6' },
  { id: 'ra4', name: 'Polar Biology', icon: '🧬', description: 'Biodiversity and ecosystems in polar regions', resourceCount: 31, color: '#4ade80' },
  { id: 'ra5', name: 'Earth Sciences', icon: '🌍', description: 'Geology, geophysics, and geochemistry of polar regions', resourceCount: 27, color: '#c084fc' },
  { id: 'ra6', name: 'Atmospheric Science', icon: '🌌', description: 'Polar atmospheric processes and space weather', resourceCount: 19, color: '#f59e0b' },
  { id: 'ra7', name: 'Biodiversity', icon: '🐧', description: 'Species diversity, conservation, and ecological studies', resourceCount: 24, color: '#f87171' },
  { id: 'ra8', name: 'Remote Sensing', icon: '📡', description: 'Satellite and aerial observation of polar regions', resourceCount: 22, color: '#a78bfa' },
];

// ── Expeditions ──
export const expeditions: Expedition[] = [
  {
    id: 'exp1',
    name: '44th Indian Scientific Expedition to Antarctica',
    expeditionNumber: 'ISEA-44',
    year: 2025,
    region: 'Antarctica',
    startDate: '2024-11-15',
    endDate: '2025-04-10',
    location: 'Maitri & Bharati Stations',
    objectives: [
      'Monitor long-term climate records at Maitri and Bharati stations',
      'Conduct Southern Ocean hydrographic surveys',
      'Study ice sheet dynamics using GPS and ground-penetrating radar',
      'Assess microbial biodiversity in Antarctic lakes',
    ],
    researchAreas: ['Climate Science', 'Glaciology', 'Oceanography', 'Polar Biology'],
    participants: ['Dr. Arjun Mehta', 'Dr. Neha Reddy', 'Dr. Vikram Singh', 'Dr. Suman Das'],
    institution: 'NCPOR',
    vessel: 'MV Vasiliy Golovnin',
    station: 'Maitri & Bharati',
    description: 'The 44th ISEA continued India\'s long-standing commitment to Antarctic research, focusing on climate monitoring, ice dynamics, ocean observations, and biological surveys. The expedition deployed advanced instrumentation at both Maitri and Bharati stations and conducted extensive field campaigns across the Schirmacher Oasis and Larsemann Hills regions.',
    imageUrl: '/images/expedition-antarctic.jpg',
    resourceCount: {
      reports: 3,
      datasets: 5,
      publications: 12,
      photographs: 84,
      videos: 6,
      learningModules: 4,
    },
    status: 'published',
  },
  {
    id: 'exp2',
    name: '14th Indian Arctic Expedition',
    expeditionNumber: 'IndARC-14',
    year: 2025,
    region: 'Arctic',
    startDate: '2025-06-01',
    endDate: '2025-09-15',
    location: 'Himadri Station, Ny-Ålesund, Svalbard',
    objectives: [
      'Investigate Arctic amplification and its teleconnections with Indian monsoon',
      'Monitor fjord ecosystem changes in Kongsfjorden',
      'Conduct permafrost studies using borehole temperature monitoring',
      'Study atmospheric aerosols and black carbon transport',
    ],
    researchAreas: ['Climate Science', 'Atmospheric Science', 'Earth Sciences'],
    participants: ['Dr. Priya Sharma', 'Dr. Ravi Kumar', 'Dr. Meera Joshi'],
    institution: 'NCPOR',
    station: 'Himadri',
    description: 'The 14th Indian Arctic Expedition focused on understanding Arctic amplification — the phenomenon where the Arctic warms faster than the global average — and its connections to the Indian monsoon system. Researchers operated from the Himadri station at Ny-Ålesund, Svalbard, one of the northernmost research settlements in the world.',
    imageUrl: '/images/expedition-arctic.jpg',
    resourceCount: {
      reports: 2,
      datasets: 4,
      publications: 8,
      photographs: 56,
      videos: 3,
      learningModules: 2,
    },
    status: 'published',
  },
  {
    id: 'exp3',
    name: '13th Indian Southern Ocean Expedition',
    expeditionNumber: 'ISOE-13',
    year: 2024,
    region: 'Southern Ocean',
    startDate: '2024-01-10',
    endDate: '2024-03-20',
    location: 'Southern Ocean, Indian Sector',
    objectives: [
      'Characterize Southern Ocean water masses and circulation patterns',
      'Deploy bio-geochemical Argo floats',
      'Study phytoplankton bloom dynamics and carbon sequestration',
      'Investigate deep-water formation processes',
    ],
    researchAreas: ['Oceanography', 'Climate Science', 'Polar Biology'],
    participants: ['Dr. Arjun Mehta', 'Dr. Suman Das', 'Dr. Anita Pillai'],
    institution: 'NCPOR',
    vessel: 'SV Sagar Nidhi',
    description: 'The 13th Indian Southern Ocean Expedition focused on understanding the Southern Ocean\'s role in global climate regulation. The expedition collected extensive hydrographic data, deployed autonomous floats, and conducted biological sampling across multiple transects in the Indian sector of the Southern Ocean.',
    imageUrl: '/images/expedition-ocean.jpg',
    resourceCount: {
      reports: 2,
      datasets: 6,
      publications: 5,
      photographs: 42,
      videos: 2,
      learningModules: 1,
    },
    status: 'published',
  },
  {
    id: 'exp4',
    name: '6th Indian Himalayan Glaciological Expedition',
    expeditionNumber: 'IHGE-6',
    year: 2024,
    region: 'Himalayas',
    startDate: '2024-05-15',
    endDate: '2024-10-30',
    location: 'Chandra Basin, Himachal Pradesh',
    objectives: [
      'Monitor mass balance of benchmark glaciers',
      'Study glacier-climate interactions',
      'Assess meltwater contribution to river systems',
      'Install automated weather stations at high altitude',
    ],
    researchAreas: ['Glaciology', 'Climate Science', 'Earth Sciences'],
    participants: ['Dr. Vikram Singh', 'Dr. Deepak Thapa'],
    institution: 'NCPOR',
    description: 'The 6th IHGE focused on monitoring Himalayan glacier health and understanding the impacts of climate change on India\'s frozen water reserves. The expedition installed new instrumentation and collected multi-year datasets from the Chandra Basin region.',
    imageUrl: '/images/expedition-himalaya.jpg',
    resourceCount: {
      reports: 1,
      datasets: 3,
      publications: 4,
      photographs: 38,
      videos: 2,
      learningModules: 1,
    },
    status: 'published',
  },
];

// ── Reports ──
export const reports: Report[] = [
  {
    id: 'rep1',
    type: 'report',
    title: 'Antarctic Sea Ice Extent and Variability: Observations from ISEA-44',
    description: 'Comprehensive analysis of sea ice concentration, extent, and seasonal variability observed during the 44th Indian Scientific Expedition to Antarctica. This report presents multi-sensor satellite and in-situ observations collected between November 2024 and April 2025.',
    abstract: 'This report documents observations of Antarctic sea ice extent and variability during the 44th Indian Scientific Expedition to Antarctica (ISEA-44). Using a combination of satellite-derived sea ice concentration data and in-situ measurements from ship-based and station-based instruments, we characterize the seasonal evolution of sea ice in the region surrounding Maitri and Bharati stations. Our observations indicate a continued trend of regional variability in sea ice patterns, with notable deviations from the long-term mean in the Prydz Bay region.',
    findings: [
      'Sea ice extent in the Indian Ocean sector showed 12% below-average values during the austral summer of 2024-25',
      'Fast ice formation around Bharati station occurred approximately 2 weeks later than the 2010-2020 average',
      'Satellite observations correlated well with ship-based measurements (r² = 0.94)',
      'First-year ice thickness measurements revealed spatial heterogeneity linked to local wind patterns',
    ],
    researchArea: 'Climate Science',
    region: 'Antarctica',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['sea ice', 'Antarctica', 'remote sensing', 'climate monitoring', 'Prydz Bay'],
    expeditionId: 'exp1',
    authors: ['Dr. Arjun Mehta', 'Dr. Neha Reddy'],
    organization: 'NCPOR',
    imageUrl: '/images/sea-ice.jpg',
    relatedPublications: ['pub1', 'pub2'],
    relatedDatasets: ['ds1', 'ds2'],
    createdAt: '2025-05-15',
    updatedAt: '2025-06-01',
  },
  {
    id: 'rep2',
    type: 'report',
    title: 'Microbial Diversity in Antarctic Freshwater Lakes: Schirmacher Oasis Survey',
    description: 'Assessment of microbial community composition and biodiversity in freshwater lakes of the Schirmacher Oasis near Maitri station, collected during ISEA-44.',
    abstract: 'We present a comprehensive survey of microbial diversity in freshwater lakes of the Schirmacher Oasis, East Antarctica. Using 16S rRNA gene amplicon sequencing, we characterized bacterial and archaeal communities across 12 lakes of varying physico-chemical properties. Our results reveal distinct community compositions correlated with water chemistry parameters and lake morphology.',
    findings: [
      'Identified over 850 operational taxonomic units (OTUs) across 12 lakes',
      'Cyanobacteria dominated in shallow, well-illuminated lakes',
      'Novel phylotypes of cold-adapted Actinobacteria were detected in deep, oligotrophic lakes',
      'Community composition showed significant correlation with dissolved oxygen and pH levels',
    ],
    researchArea: 'Polar Biology',
    region: 'Antarctica',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['microbial diversity', 'freshwater lakes', 'Schirmacher Oasis', 'metagenomics', 'extremophiles'],
    expeditionId: 'exp1',
    authors: ['Dr. Suman Das', 'Dr. Vikram Singh'],
    organization: 'NCPOR',
    imageUrl: '/images/microbial.jpg',
    relatedPublications: ['pub3'],
    relatedDatasets: ['ds3'],
    createdAt: '2025-06-10',
    updatedAt: '2025-07-01',
  },
  {
    id: 'rep3',
    type: 'report',
    title: 'Arctic Amplification and Indian Monsoon Teleconnections: Himadri Station Observations',
    description: 'Analysis of Arctic temperature amplification trends and their potential teleconnections with the Indian Summer Monsoon, based on observations from IndARC-14.',
    abstract: 'This report examines observational evidence for Arctic amplification — the enhanced warming of the Arctic relative to the global average — and explores potential teleconnection pathways linking Arctic climate changes to variability in the Indian Summer Monsoon. Using multi-year meteorological data from the Himadri station, supplemented by reanalysis products and satellite observations, we identify correlations between Arctic sea ice decline and monsoon onset timing.',
    findings: [
      'Surface temperature trends at Himadri station show warming of 0.8°C per decade over the past 15 years',
      'Statistically significant correlations found between September Arctic sea ice extent and subsequent monsoon onset timing',
      'Atmospheric wave patterns suggest a Rossby wave pathway connecting Arctic warming to South Asian circulation',
      'Black carbon aerosol measurements show seasonal peaks coinciding with Eurasian biomass burning events',
    ],
    researchArea: 'Climate Science',
    region: 'Arctic',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['Arctic amplification', 'Indian monsoon', 'teleconnections', 'climate change', 'Svalbard'],
    expeditionId: 'exp2',
    authors: ['Dr. Priya Sharma', 'Dr. Ravi Kumar'],
    organization: 'NCPOR',
    imageUrl: '/images/arctic-research.jpg',
    relatedPublications: ['pub4'],
    relatedDatasets: ['ds4', 'ds5'],
    createdAt: '2025-10-01',
    updatedAt: '2025-10-15',
  },
];

// ── Datasets ──
export const datasets: Dataset[] = [
  {
    id: 'ds1',
    type: 'dataset',
    title: 'Antarctic Sea Ice Concentration — Indian Ocean Sector (2024-25)',
    description: 'Daily sea ice concentration data derived from satellite passive microwave observations for the Indian Ocean sector of Antarctica during the austral summer season 2024-25.',
    researchArea: 'Climate Science',
    region: 'Antarctica',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['sea ice concentration', 'satellite data', 'passive microwave', 'time series'],
    expeditionId: 'exp1',
    authors: ['Dr. Arjun Mehta'],
    datasetType: 'Time Series',
    collectionPeriod: 'November 2024 – April 2025',
    geographicCoverage: '60°S–70°S, 40°E–100°E',
    variables: ['Sea Ice Concentration (%)', 'Date', 'Latitude', 'Longitude', 'Sensor'],
    units: ['%', 'YYYY-MM-DD', '°S', '°E', 'categorical'],
    fileFormat: 'CSV',
    license: 'CC BY 4.0',
    citation: 'Mehta, A. et al. (2025). Antarctic Sea Ice Concentration Dataset — ISEA-44. NCPOR Data Repository.',
    rowCount: 18250,
    columnCount: 5,
    imageUrl: '/images/dataset-seaice.jpg',
    createdAt: '2025-05-20',
    updatedAt: '2025-05-20',
  },
  {
    id: 'ds2',
    type: 'dataset',
    title: 'Ship-Based Sea Ice Thickness Measurements — ISEA-44 Transit',
    description: 'In-situ measurements of sea ice thickness along the ship transit route during ISEA-44, collected using electromagnetic induction (EM) sled deployed from the vessel.',
    researchArea: 'Glaciology',
    region: 'Antarctica',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['sea ice thickness', 'EM measurements', 'ship-based', 'in-situ'],
    expeditionId: 'exp1',
    authors: ['Dr. Neha Reddy'],
    datasetType: 'Transect',
    collectionPeriod: 'December 2024 – February 2025',
    geographicCoverage: 'Ship transit route (Cape Town to Bharati Station)',
    variables: ['Ice Thickness (m)', 'Snow Depth (m)', 'Latitude', 'Longitude', 'Date', 'Ice Type'],
    units: ['m', 'm', '°S', '°E', 'YYYY-MM-DD', 'categorical'],
    fileFormat: 'CSV',
    license: 'CC BY 4.0',
    citation: 'Reddy, N. (2025). Ship-Based Sea Ice Thickness — ISEA-44. NCPOR Data Repository.',
    rowCount: 4820,
    columnCount: 6,
    createdAt: '2025-06-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'ds3',
    type: 'dataset',
    title: 'Microbial Community Composition — Schirmacher Oasis Lakes',
    description: '16S rRNA amplicon sequencing data from water samples collected across 12 freshwater lakes in the Schirmacher Oasis.',
    researchArea: 'Polar Biology',
    region: 'Antarctica',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['16S rRNA', 'amplicon sequencing', 'microbial diversity', 'OTU table'],
    expeditionId: 'exp1',
    authors: ['Dr. Suman Das'],
    datasetType: 'Genomic',
    collectionPeriod: 'January – February 2025',
    geographicCoverage: 'Schirmacher Oasis, 70.75°S, 11.73°E',
    variables: ['OTU_ID', 'Taxonomy', 'Lake_ID', 'Relative_Abundance', 'Sample_Depth'],
    units: ['categorical', 'categorical', 'categorical', '%', 'm'],
    fileFormat: 'CSV',
    license: 'CC BY 4.0',
    citation: 'Das, S. (2025). Microbial Community Data — Schirmacher Oasis. NCPOR Data Repository.',
    rowCount: 10240,
    columnCount: 5,
    createdAt: '2025-07-01',
    updatedAt: '2025-07-01',
  },
  {
    id: 'ds4',
    type: 'dataset',
    title: 'Himadri Station Meteorological Records (2020–2025)',
    description: 'Five-year continuous meteorological observations from India\'s Himadri station at Ny-Ålesund, Svalbard, including temperature, humidity, wind, and radiation parameters.',
    researchArea: 'Atmospheric Science',
    region: 'Arctic',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['meteorology', 'Arctic', 'Svalbard', 'time series', 'climate monitoring'],
    expeditionId: 'exp2',
    authors: ['Dr. Ravi Kumar'],
    datasetType: 'Time Series',
    collectionPeriod: '2020–2025',
    geographicCoverage: 'Ny-Ålesund, Svalbard (78.92°N, 11.93°E)',
    variables: ['Temperature (°C)', 'Relative Humidity (%)', 'Wind Speed (m/s)', 'Wind Direction (°)', 'Solar Radiation (W/m²)', 'Pressure (hPa)'],
    units: ['°C', '%', 'm/s', '°', 'W/m²', 'hPa'],
    fileFormat: 'CSV',
    license: 'CC BY 4.0',
    citation: 'Kumar, R. (2025). Himadri Station Meteorological Data. NCPOR Data Repository.',
    rowCount: 43800,
    columnCount: 7,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-05',
  },
  {
    id: 'ds5',
    type: 'dataset',
    title: 'Southern Ocean CTD Profiles — ISOE-13',
    description: 'Conductivity-Temperature-Depth (CTD) profiles collected during the 13th Indian Southern Ocean Expedition across multiple transects.',
    researchArea: 'Oceanography',
    region: 'Southern Ocean',
    year: 2024,
    status: 'published',
    visibility: 'public',
    keywords: ['CTD', 'hydrography', 'Southern Ocean', 'water masses', 'ocean circulation'],
    expeditionId: 'exp3',
    authors: ['Dr. Arjun Mehta', 'Dr. Anita Pillai'],
    datasetType: 'Profiles',
    collectionPeriod: 'January – March 2024',
    geographicCoverage: '40°S–65°S, 50°E–80°E',
    variables: ['Depth (m)', 'Temperature (°C)', 'Salinity (PSU)', 'Dissolved Oxygen (ml/L)', 'Station_ID', 'Latitude', 'Longitude'],
    units: ['m', '°C', 'PSU', 'ml/L', 'categorical', '°', '°'],
    fileFormat: 'CSV',
    license: 'CC BY 4.0',
    citation: 'Mehta, A. & Pillai, A. (2024). Southern Ocean CTD Profiles — ISOE-13. NCPOR Data Repository.',
    rowCount: 28500,
    columnCount: 7,
    createdAt: '2024-06-15',
    updatedAt: '2024-06-15',
  },
];

// ── Publications ──
export const publications: Publication[] = [
  {
    id: 'pub1',
    type: 'publication',
    title: 'Declining sea ice trends in the Indian Ocean sector of Antarctica: A satellite-based assessment (2015–2025)',
    description: 'A comprehensive satellite-based assessment of sea ice trends in the Indian Ocean sector over the past decade.',
    abstract: 'We present a decade-long assessment of sea ice extent, concentration, and seasonal patterns in the Indian Ocean sector of Antarctica using passive microwave satellite data. Results indicate statistically significant declining trends in summer sea ice extent, with implications for regional ocean circulation and ecosystem dynamics.',
    researchArea: 'Climate Science',
    region: 'Antarctica',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['sea ice trends', 'satellite assessment', 'Indian Ocean sector', 'decadal analysis'],
    journal: 'Journal of Glaciology',
    doi: '10.xxxx/demo-doi-001',
    publicationDate: '2025-07-15',
    relatedExpedition: 'exp1',
    datasetReferences: ['ds1', 'ds2'],
    authors: ['Dr. Arjun Mehta', 'Dr. Neha Reddy', 'Dr. Priya Sharma'],
    createdAt: '2025-07-15',
    updatedAt: '2025-07-15',
  },
  {
    id: 'pub2',
    type: 'publication',
    title: 'First-year ice thickness distribution near Bharati Station: Observations and modeling',
    description: 'Combined observational and modeling study of first-year sea ice thickness in the Prydz Bay region near India\'s Bharati station.',
    abstract: 'We combine ship-based electromagnetic induction measurements of sea ice thickness with a thermodynamic sea ice model to characterize first-year ice growth patterns near Bharati Station in Prydz Bay, East Antarctica.',
    researchArea: 'Glaciology',
    region: 'Antarctica',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['ice thickness', 'Prydz Bay', 'Bharati Station', 'thermodynamic model'],
    journal: 'Cold Regions Science and Technology',
    doi: '10.xxxx/demo-doi-002',
    publicationDate: '2025-08-20',
    relatedExpedition: 'exp1',
    datasetReferences: ['ds2'],
    authors: ['Dr. Neha Reddy', 'Dr. Arjun Mehta'],
    createdAt: '2025-08-20',
    updatedAt: '2025-08-20',
  },
  {
    id: 'pub3',
    type: 'publication',
    title: 'Cold-adapted Actinobacteria from Antarctic freshwater lakes: Phylogenetic diversity and enzymatic potential',
    description: 'Discovery and characterization of novel cold-adapted Actinobacteria from Schirmacher Oasis lakes.',
    abstract: 'We report the isolation and characterization of cold-adapted Actinobacteria from freshwater lakes in the Schirmacher Oasis. Phylogenetic analysis reveals novel lineages with cold-active enzyme production capabilities of potential biotechnological interest.',
    researchArea: 'Polar Biology',
    region: 'Antarctica',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['Actinobacteria', 'cold-adapted', 'enzymes', 'biotechnology', 'Antarctic lakes'],
    journal: 'Extremophiles',
    doi: '10.xxxx/demo-doi-003',
    publicationDate: '2025-09-01',
    relatedExpedition: 'exp1',
    datasetReferences: ['ds3'],
    authors: ['Dr. Suman Das', 'Dr. Vikram Singh'],
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    id: 'pub4',
    type: 'publication',
    title: 'Arctic-monsoon teleconnections: Evidence from Svalbard observations and reanalysis products',
    description: 'Investigation of statistical and dynamical connections between Arctic climate variability and the Indian monsoon.',
    abstract: 'Using multi-year observational data from the Himadri station in Svalbard combined with ERA5 reanalysis products, we identify statistically significant teleconnection pathways between Arctic climate variability and the Indian Summer Monsoon.',
    researchArea: 'Climate Science',
    region: 'Arctic',
    year: 2025,
    status: 'published',
    visibility: 'public',
    keywords: ['Arctic-monsoon', 'teleconnections', 'Svalbard', 'ERA5', 'Rossby waves'],
    journal: 'Nature Climate Change',
    doi: '10.xxxx/demo-doi-004',
    publicationDate: '2025-11-01',
    relatedExpedition: 'exp2',
    datasetReferences: ['ds4'],
    authors: ['Dr. Priya Sharma', 'Dr. Ravi Kumar', 'Dr. Meera Joshi'],
    createdAt: '2025-11-01',
    updatedAt: '2025-11-01',
  },
];

// ── Photographs ──
export const photographs: Photograph[] = [
  {
    id: 'photo1', type: 'photograph', title: 'Bharati Station Under Aurora Australis',
    description: 'A stunning view of India\'s Bharati research station illuminated by the southern lights during the polar winter.',
    researchArea: 'Atmospheric Science', region: 'Antarctica', year: 2025,
    status: 'published', visibility: 'public',
    keywords: ['aurora australis', 'Bharati station', 'polar night'],
    expeditionId: 'exp1', photographer: 'Dr. Neha Reddy',
    date: '2025-06-21', location: 'Bharati Station, Larsemann Hills',
    tags: ['aurora', 'station', 'night', 'polar'], copyright: 'NCPOR / CC BY 4.0',
    highResUrl: '/images/aurora-bharati.jpg', imageUrl: '/images/aurora-bharati.jpg',
    createdAt: '2025-06-22', updatedAt: '2025-06-22',
  },
  {
    id: 'photo2', type: 'photograph', title: 'Emperor Penguin Colony Near Maitri',
    description: 'Emperor penguins gathered near a freshwater source in the vicinity of Maitri Station, photographed during ISEA-44.',
    researchArea: 'Biodiversity', region: 'Antarctica', year: 2025,
    status: 'published', visibility: 'public',
    keywords: ['emperor penguin', 'colony', 'wildlife'],
    expeditionId: 'exp1', photographer: 'Dr. Vikram Singh',
    date: '2025-01-15', location: 'Near Maitri Station, Schirmacher Oasis',
    tags: ['penguins', 'wildlife', 'biodiversity'], copyright: 'NCPOR / CC BY 4.0',
    highResUrl: '/images/penguins.jpg', imageUrl: '/images/penguins.jpg',
    createdAt: '2025-01-16', updatedAt: '2025-01-16',
  },
  {
    id: 'photo3', type: 'photograph', title: 'Ice Core Sampling at Bharati',
    description: 'Researchers extracting an ice core sample from the coastal ice shelf near Bharati Station.',
    researchArea: 'Glaciology', region: 'Antarctica', year: 2025,
    status: 'published', visibility: 'public',
    keywords: ['ice core', 'glaciology', 'fieldwork'],
    expeditionId: 'exp1', photographer: 'Dr. Arjun Mehta',
    date: '2025-02-10', location: 'Near Bharati Station',
    tags: ['ice core', 'research', 'field work'], copyright: 'NCPOR / CC BY 4.0',
    highResUrl: '/images/ice-core.jpg', imageUrl: '/images/ice-core.jpg',
    createdAt: '2025-02-11', updatedAt: '2025-02-11',
  },
  {
    id: 'photo4', type: 'photograph', title: 'Midnight Sun Over Himadri Station',
    description: 'The phenomenon of the midnight sun captured over India\'s Himadri station at Ny-Ålesund during the Arctic summer.',
    researchArea: 'Atmospheric Science', region: 'Arctic', year: 2025,
    status: 'published', visibility: 'public',
    keywords: ['midnight sun', 'Arctic', 'Himadri'],
    expeditionId: 'exp2', photographer: 'Dr. Priya Sharma',
    date: '2025-06-21', location: 'Ny-Ålesund, Svalbard',
    tags: ['midnight sun', 'Arctic', 'Svalbard'], copyright: 'NCPOR / CC BY 4.0',
    highResUrl: '/images/midnight-sun.jpg', imageUrl: '/images/midnight-sun.jpg',
    createdAt: '2025-06-22', updatedAt: '2025-06-22',
  },
];

// ── Videos ──
export const videos: Video[] = [
  {
    id: 'vid1', type: 'video', title: 'Inside Bharati Station: Life at the Edge of Antarctica',
    description: 'A documentary-style tour of India\'s Bharati research station, showing the living quarters, laboratories, and daily life of researchers during the Antarctic winter.',
    researchArea: 'Earth Sciences', region: 'Antarctica', year: 2025,
    status: 'published', visibility: 'public',
    keywords: ['Bharati station', 'Antarctic life', 'documentary'],
    expeditionId: 'exp1', duration: '12:34',
    thumbnailUrl: '/images/bharati-video.jpg', source: 'NCPOR Media',
    imageUrl: '/images/bharati-video.jpg',
    createdAt: '2025-04-15', updatedAt: '2025-04-15',
  },
  {
    id: 'vid2', type: 'video', title: 'Deploying Argo Floats in the Southern Ocean',
    description: 'Footage of the deployment of bio-geochemical Argo floats during the 13th Indian Southern Ocean Expedition.',
    researchArea: 'Oceanography', region: 'Southern Ocean', year: 2024,
    status: 'published', visibility: 'public',
    keywords: ['Argo floats', 'Southern Ocean', 'oceanography'],
    expeditionId: 'exp3', duration: '08:22',
    thumbnailUrl: '/images/argo-deploy.jpg', source: 'NCPOR Media',
    imageUrl: '/images/argo-deploy.jpg',
    createdAt: '2024-04-10', updatedAt: '2024-04-10',
  },
];

// ── Learning Modules ──
export const learningModules: LearningModule[] = [
  {
    id: 'lm1', title: 'What is Sea Ice and Why Does It Matter?',
    description: 'An introductory module explaining sea ice formation, types, and its role in the global climate system.',
    difficulty: 'beginner', topics: ['Sea Ice', 'Climate', 'Antarctica'],
    targetAudience: 'School Students', estimatedTime: '15 min',
    imageUrl: '/images/learn-seaice.jpg', sourceResources: ['rep1', 'ds1'],
  },
  {
    id: 'lm2', title: 'Life in Extreme Cold: Antarctic Microbes',
    description: 'Discover how microscopic organisms survive in one of the coldest places on Earth — Antarctic freshwater lakes.',
    difficulty: 'beginner', topics: ['Microbiology', 'Extremophiles', 'Antarctica'],
    targetAudience: 'School Students', estimatedTime: '20 min',
    imageUrl: '/images/learn-microbes.jpg', sourceResources: ['rep2', 'ds3'],
  },
  {
    id: 'lm3', title: 'Understanding Arctic Amplification',
    description: 'Why is the Arctic warming faster than the rest of the planet? This module explains the science behind Arctic amplification.',
    difficulty: 'intermediate', topics: ['Arctic', 'Climate Change', 'Amplification'],
    targetAudience: 'University Students', estimatedTime: '25 min',
    imageUrl: '/images/learn-arctic.jpg', sourceResources: ['rep3', 'ds4'],
  },
  {
    id: 'lm4', title: 'India\'s Polar Research Stations',
    description: 'A visual tour of India\'s research stations — Maitri and Bharati in Antarctica, and Himadri in the Arctic.',
    difficulty: 'beginner', topics: ['Research Stations', 'India', 'NCPOR'],
    targetAudience: 'General Public', estimatedTime: '10 min',
    imageUrl: '/images/learn-stations.jpg', sourceResources: ['exp1', 'exp2'],
  },
];

// ── Glossary ──
export const glossaryTerms: GlossaryTerm[] = [
  { id: 'g1', term: 'Cryosphere', definition: 'The portions of Earth\'s surface where water is in solid form, including ice sheets, glaciers, sea ice, snow cover, and permafrost.', simpleExplanation: 'All the frozen parts of our planet — ice caps, glaciers, frozen oceans, snow, and frozen ground.', relatedTerms: ['Sea Ice', 'Glacier', 'Permafrost'], relatedResources: ['rep1', 'ds1'] },
  { id: 'g2', term: 'Sea Ice', definition: 'Frozen ocean water that forms, grows, and melts in the ocean. It differs from icebergs, glaciers, and ice shelves, which originate on land.', simpleExplanation: 'When the ocean gets cold enough, the water at the surface freezes and becomes sea ice — like a frozen lid on the ocean.', relatedTerms: ['Cryosphere', 'Fast Ice', 'Pack Ice'], relatedResources: ['rep1', 'ds1', 'ds2'] },
  { id: 'g3', term: 'Arctic Amplification', definition: 'The phenomenon whereby the Arctic region warms at a rate significantly faster than the global average, primarily driven by ice-albedo feedback mechanisms.', simpleExplanation: 'The Arctic is warming much faster than the rest of the world. When ice melts, darker ocean water absorbs more heat, which melts even more ice — creating a warming loop.', relatedTerms: ['Albedo', 'Climate Change', 'Teleconnection'], relatedResources: ['rep3', 'ds4'] },
  { id: 'g4', term: 'Extremophile', definition: 'An organism that thrives in physically or geochemically extreme conditions that are detrimental to most life on Earth.', simpleExplanation: 'Tiny living things that love extreme places — super cold, super hot, very salty, or very acidic environments where most life can\'t survive.', relatedTerms: ['Psychrophile', 'Microbial Diversity'], relatedResources: ['rep2', 'ds3'] },
  { id: 'g5', term: 'CTD', definition: 'An oceanographic instrument used to measure Conductivity, Temperature, and Depth of seawater. CTD data are fundamental to characterizing ocean water masses.', simpleExplanation: 'A special instrument that scientists lower into the ocean to measure how salty, warm, and deep the water is at different levels.', relatedTerms: ['Hydrography', 'Water Mass'], relatedResources: ['ds5'] },
  { id: 'g6', term: 'Teleconnection', definition: 'A statistical and/or physical relationship between climate anomalies at widely separated geographic locations on Earth.', simpleExplanation: 'When weather changes in one part of the world can affect weather far away — like how melting Arctic ice might change when the Indian monsoon arrives.', relatedTerms: ['Arctic Amplification', 'Monsoon'], relatedResources: ['rep3', 'pub4'] },
];

// ── Notifications ──
export const notifications: Notification[] = [
  { id: 'n1', type: 'upload_complete', title: 'Document Processed', message: 'Antarctic Sea Ice Observation Report has been processed and indexed.', read: false, timestamp: '2025-10-01T10:30:00Z', resourceId: 'rep1' },
  { id: 'n2', type: 'review_required', title: 'Metadata Review Required', message: 'AI-extracted metadata for "Microbial Diversity Report" needs your review.', read: false, timestamp: '2025-10-01T09:15:00Z', resourceId: 'rep2' },
  { id: 'n3', type: 'published', title: 'Content Published', message: 'Research highlight for Arctic Amplification study has been published.', read: true, timestamp: '2025-09-30T14:00:00Z', resourceId: 'rep3' },
  { id: 'n4', type: 'approval_required', title: 'Outreach Content Ready', message: 'LinkedIn post draft for Sea Ice report is ready for your approval.', read: false, timestamp: '2025-10-01T08:45:00Z' },
];

// ── Sample Outreach Package ──
export const sampleOutreachPackage: OutreachPackage = {
  id: 'op1',
  sourceResourceId: 'rep1',
  sourceResourceTitle: 'Antarctic Sea Ice Extent and Variability: Observations from ISEA-44',
  status: 'draft',
  createdAt: '2025-10-01',
  outputs: [
    {
      id: 'oo1', type: 'research_highlight',
      title: 'New Observations Reveal Declining Sea Ice in Indian Ocean Sector of Antarctica',
      content: 'Scientists from NCPOR have documented continued decline in sea ice extent in the Indian Ocean sector of Antarctica during their latest expedition. The 44th Indian Scientific Expedition to Antarctica (ISEA-44) found that summer sea ice extent was approximately 12% below the long-term average, with notable changes in ice formation timing around India\'s Bharati research station.\n\nThe findings, based on both satellite observations and direct field measurements, contribute to the growing body of evidence showing rapid changes in Antarctic sea ice patterns. "The close agreement between our satellite-derived and ship-based measurements gives us high confidence in these observations," noted the research team.\n\nOf particular interest was the finding that fast ice — sea ice attached to the coast — formed approximately two weeks later than the 2010-2020 average near Bharati Station, suggesting warming trends in the coastal marine environment of the Prydz Bay region.',
      status: 'ai_generated', generatedAt: '2025-10-01',
    },
    {
      id: 'oo2', type: 'website_article',
      title: 'Antarctica\'s Shrinking Ice: What India\'s Latest Expedition Discovered',
      content: '## Antarctica\'s Shrinking Ice: What India\'s Latest Expedition Discovered\n\nEvery year, India sends scientists to one of the most remote places on Earth — Antarctica. During the 44th Indian Scientific Expedition to Antarctica, researchers made important observations about how the frozen ocean around the continent is changing.\n\n### What Is Sea Ice?\n\nSea ice is frozen ocean water. Unlike icebergs that break off from glaciers on land, sea ice forms when the ocean surface gets cold enough to freeze. It acts like a giant mirror, reflecting sunlight back into space and helping to keep our planet cool.\n\n### What Did Scientists Find?\n\nThe expedition team found that the area covered by sea ice in the Indian Ocean sector of Antarctica was about 12% less than the average of recent years. They also noticed that ice near India\'s Bharati station started forming about two weeks later than usual.\n\n### Why Does This Matter?\n\nSea ice plays a crucial role in Earth\'s climate. When there\'s less sea ice, more sunlight is absorbed by the dark ocean water, which warms it further — creating a cycle of warming. Changes in Antarctic sea ice can affect ocean currents, weather patterns, and marine ecosystems thousands of kilometers away.\n\n### How Did They Measure It?\n\nScientists used two methods: satellite images that show ice from space, and special instruments on their research vessel that measure ice thickness directly. The two methods agreed closely, giving scientists confidence in their findings.\n\n---\n\n*Based on observations from the 44th Indian Scientific Expedition to Antarctica (ISEA-44). Source: NCPOR.*',
      status: 'ai_generated', generatedAt: '2025-10-01',
    },
    {
      id: 'oo3', type: 'linkedin',
      title: 'LinkedIn Post — Sea Ice Research',
      content: '🧊 New findings from India\'s 44th Antarctic Expedition (ISEA-44):\n\nOur team at NCPOR observed a 12% below-average sea ice extent in the Indian Ocean sector of Antarctica during the 2024-25 austral summer.\n\nKey observations:\n📊 Ship-based and satellite measurements showed excellent agreement (r² = 0.94)\n🕐 Fast ice formation near Bharati Station delayed by ~2 weeks compared to the decadal average\n🌊 Spatial variability in first-year ice linked to local wind patterns\n\nThese observations contribute to our understanding of how Antarctic sea ice is evolving and its implications for global climate.\n\n#PolarScience #Antarctica #ClimateResearch #NCPOR #SeaIce #IndianExpedition',
      status: 'ai_generated', generatedAt: '2025-10-01',
    },
    {
      id: 'oo4', type: 'instagram',
      title: 'Instagram Caption — Sea Ice',
      content: '🌊🧊 Antarctica\'s frozen ocean is changing.\n\nDuring India\'s 44th Antarctic Expedition, our scientists found 12% less sea ice than average in the Indian Ocean sector.\n\nSea ice acts as Earth\'s mirror — when it shrinks, our planet absorbs more heat. Understanding these changes is why India sends researchers to one of the coldest, most remote places on Earth every year.\n\n📸 Sea ice observations from ISEA-44\n\n#Antarctica #SeaIce #PolarScience #ClimateChange #NCPOR #IndianExpedition #ScienceMatters',
      status: 'ai_generated', generatedAt: '2025-10-01',
    },
    {
      id: 'oo5', type: 'student_explanation',
      title: 'Student Explanation — Sea Ice Changes',
      content: '## Why Is Antarctic Sea Ice Getting Smaller?\n\n### The Simple Version\nImagine the ocean around Antarctica as a giant pond. Every winter, the surface of this pond freezes over — this is called sea ice. Every summer, some of it melts. But scientists from India noticed that this "frozen lid" on the ocean is getting smaller over time.\n\n### What Did Indian Scientists Find?\nDuring India\'s latest expedition to Antarctica (their 44th!), scientists found that the frozen area of the ocean was about 12% smaller than what\'s been normal in recent years. They also noticed that the ice started forming later than usual — about 2 weeks late.\n\n### Why Should We Care?\nSea ice is like a giant mirror. It reflects sunlight back into space, which helps keep Earth cool. When there\'s less sea ice, more sunlight hits the dark ocean water, which absorbs the heat instead of reflecting it. This makes the water warmer, which melts even more ice. It\'s like a cycle that keeps making things warmer.\n\n### Cool Fact!\nScientists measured the ice from their ship AND from satellites in space — and both methods gave almost exactly the same answers! This is how science works: checking your results in multiple ways.',
      status: 'ai_generated', generatedAt: '2025-10-01',
    },
    {
      id: 'oo6', type: 'data_reel',
      title: 'Data-to-Reel: Sea Ice Extent Timelapse',
      content: '🎬 [ANIMATED REEL PREVIEW]\nThis output transforms the "Sea Ice Concentration 2024-25" dataset into a dynamic 15-second social media reel.\n\nVisuals: A spinning globe zooms into the Indian Ocean sector of Antarctica. A time-lapse animation shows the sea ice advancing and retreating over the season, with a heat-map overlay highlighting the 12% deficit compared to the 10-year average.\n\nAudio: Modern, upbeat synth track.\n\nCaption Generator: "Watch how Antarctica\'s ice breathes over a year... but this year, it\'s struggling to catch its breath. 🧊📉 Data from India\'s latest expedition shows a 12% drop in sea ice. #DataViz #ClimateAction #Antarctica"',
      status: 'ai_generated', generatedAt: '2025-10-01',
    },
    {
      id: 'oo7', type: 'data_sonification',
      title: 'Data Sonification: "Listening" to the Ice Melt',
      content: '🔊 [AUDIO SONIFICATION PREVIEW]\nThis output maps the temperature and sea-ice thickness dataset into an auditory experience for visually impaired learners and auditory engagement.\n\nMapping Parameters:\n- Pitch = Sea ice thickness (higher pitch = thinner ice)\n- Tempo = Rate of melting (faster tempo = rapid melt)\n- Volume/Intensity = Temperature anomalies (louder = warmer than average)\n\nDescription: The audio begins with slow, deep, resonant tones representing the stable winter ice of 2010. As the timeline progresses toward 2025, the tempo accelerates, the pitch rises uncomfortably, and a rushing wind sound grows louder, viscerally demonstrating the rapid loss of thick, multi-year ice and the warming anomalies recorded during ISEA-44.',
      status: 'ai_generated', generatedAt: '2025-10-01',
    }
  ],
};

// ── Sample Quiz ──
export const sampleQuiz: Quiz = {
  id: 'quiz1',
  title: 'Test Your Knowledge: Antarctic Sea Ice',
  sourceResourceId: 'rep1',
  difficulty: 'easy',
  questions: [
    {
      id: 'q1', question: 'What is sea ice?',
      options: ['Ice that breaks off from glaciers on land', 'Frozen ocean water that forms on the sea surface', 'Snow that falls on the ocean', 'Ice imported from the Arctic'],
      correctAnswer: 1, explanation: 'Sea ice forms when the ocean surface gets cold enough to freeze. It\'s different from icebergs, which break off from land-based glaciers.',
    },
    {
      id: 'q2', question: 'According to ISEA-44 observations, how much below average was the sea ice extent?',
      options: ['5%', '8%', '12%', '20%'],
      correctAnswer: 2, explanation: 'The observations showed that sea ice extent in the Indian Ocean sector was approximately 12% below the long-term average during the 2024-25 austral summer.',
      sourceReference: 'Antarctic Sea Ice Observation Report, Finding 1',
    },
    {
      id: 'q3', question: 'What is "fast ice"?',
      options: ['Ice that moves very quickly', 'Sea ice that is attached to the coastline', 'Ice that forms and melts rapidly', 'A type of glacier'],
      correctAnswer: 1, explanation: 'Fast ice is sea ice that is attached, or "fastened," to the coastline, sea floor, or to grounded icebergs.',
    },
    {
      id: 'q4', question: 'Why does sea ice matter for climate?',
      options: ['It provides fresh water', 'It reflects sunlight and helps regulate Earth\'s temperature', 'It prevents ships from sailing', 'It produces oxygen'],
      correctAnswer: 1, explanation: 'Sea ice has a high albedo (reflectivity), meaning it reflects solar radiation back into space. When ice melts, the darker ocean absorbs more heat, accelerating warming.',
    },
    {
      id: 'q5', question: 'Which Indian research station is located in the Larsemann Hills region of Antarctica?',
      options: ['Maitri', 'Bharati', 'Himadri', 'Dakshin Gangotri'],
      correctAnswer: 1, explanation: 'India\'s Bharati station is located in the Larsemann Hills region of East Antarctica. It was commissioned in 2012.',
    },
  ],
};

// ── Platform Statistics ──
export const platformStats = {
  totalResources: 1248,
  expeditions: 24,
  publications: 186,
  datasets: 74,
  mediaAssets: 2430,
  learningResources: 68,
  aiQueries: 3842,
  label: 'Prototype Dataset',
};

// ── Helper ──
export function getAllResources(): Resource[] {
  return [
    ...reports,
    ...datasets,
    ...publications,
    ...photographs,
    ...videos,
  ];
}

export function getResourceById(id: string): Resource | undefined {
  return getAllResources().find(r => r.id === id);
}

export function getExpeditionById(id: string): Expedition | undefined {
  return expeditions.find(e => e.id === id);
}

export function getRelatedResources(expeditionId: string): Resource[] {
  return getAllResources().filter(r => r.expeditionId === expeditionId);
}

export function searchResources(query: string): Resource[] {
  const q = query.toLowerCase();
  return getAllResources().filter(r =>
    r.title.toLowerCase().includes(q) ||
    r.description.toLowerCase().includes(q) ||
    r.keywords.some(k => k.toLowerCase().includes(q)) ||
    r.researchArea.toLowerCase().includes(q)
  );
}
